# Generated by Django 3.1.6 on 2022-09-14 09:02

import django.core.validators
from django.db import migrations, models
import mortgage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Нименование кредитного заведения')),
                ('term_min', models.PositiveSmallIntegerField(help_text='Введите срок ипотеки. Срок не может быть менее 1 года и не может превышать 30 лет', validators=[django.core.validators.MinValueValidator(1, message='Минимальный срок ипотеки не может быть менее 1 года'), django.core.validators.MaxValueValidator(30, message='Максимальный срок ипотеки не должен превышать 30 лет')], verbose_name='Срок ипотеки лет, ОТ')),
                ('term_max', models.PositiveSmallIntegerField(help_text='Введите срок ипотеки. Срок не может быть менее 1 года и не может превышать 30 лет', validators=[django.core.validators.MinValueValidator(1, message='Минимальный срок ипотеки не может быть менее 1 года'), django.core.validators.MaxValueValidator(30, message='Максимальный срок ипотеки не должен превышать 30 лет')], verbose_name='Срок ипотеки лет, ДО')),
                ('rate_min', models.FloatField(validators=[mortgage.models.validate_positive_value], verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(validators=[mortgage.models.validate_positive_value], verbose_name='Ставка, ДО')),
                ('payment_min', models.PositiveIntegerField(validators=[mortgage.models.validate_positive_value], verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.PositiveIntegerField(validators=[mortgage.models.validate_positive_value], verbose_name='Сумма кредита, ДО')),
            ],
            options={
                'verbose_name': 'Предложения',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
